#数据库访问配置
#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    #连接池配置
    initialSize: 5
    maxActive: 100
    minIdle: 3
    maxWait: 50000
    db-type: com.alibaba.druid.pool.DruidDataSource
  #  mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp

  thymeleaf:
    cache: false
    prefix: /WEB-INF/view/
    suffix: .html
#    template-resolver-order: 1
#    mode: HTML5

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0



mybatis-plus:
#  mapper-locations: classpath:com/example/mapper/*Mapper.xml,classpath:/mybatis/*Mapper.xml
  mapper-locations: classpath:/mybatis/*Mapper.xml   #classpath*:/mybatis/*Mapper.xml
  type-aliases-package: com.example.po,com.example.vo
  global-config:
    #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid）
    id-type: 0
    refresh-mapper: true
#    表名、是否使用下划线命名，默认数据库表使用下划线命名
#    db-column-underline: true
#    表名前缀
#    table-prefix: t_

